<a href="https://colab.research.google.com/github/marine-triquet/pytorch/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
tensor_1 = torch.rand(7,7)
tensor_1, tensor_1.shape

(tensor([[0.6243, 0.0422, 0.2208, 0.8031, 0.1125, 0.3193, 0.1472],
         [0.0350, 0.0298, 0.7475, 0.5961, 0.4615, 0.5449, 0.1573],
         [0.4511, 0.4575, 0.0795, 0.5172, 0.2650, 0.9540, 0.9275],
         [0.0615, 0.9516, 0.6100, 0.0285, 0.1156, 0.6376, 0.2555],
         [0.1374, 0.6351, 0.5617, 0.4286, 0.9907, 0.3435, 0.3854],
         [0.2745, 0.2447, 0.1348, 0.4452, 0.3225, 0.1401, 0.3483],
         [0.6696, 0.8703, 0.5815, 0.0600, 0.6067, 0.7619, 0.4580]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [7]:
# Create another random tensor
tensor_2 = torch.rand(1, 7)
tensor_2, tensor_2.shape

# Perform matrix multiplication
tensor_1.shape, tensor_2.T.shape
tensor_1 @ tensor_2.T

tensor([[0.5325],
        [0.7212],
        [0.8536],
        [0.6705],
        [0.8609],
        [0.4529],
        [1.1008]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [16]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
tensor_3 = torch.rand(7, 7)

torch.manual_seed(RANDOM_SEED)
tensor_4 = torch.rand(1, 7)

tensor_3,tensor_3.shape, tensor_4, tensor_4.shape

# Matrix multiply tensors

tensor_result = torch.matmul(tensor_3, tensor_4.T) #tensor_result = tensor_3 @ tensor_4.T
tensor_result, tensor_result.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [17]:
# Set random seed on the GPU
random_seed = 1234
torch.cuda.seed(random_seed)

# https://pytorch.org/docs/stable/generated/torch.cuda.seed.html


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [20]:
# Set random seed
random_seed = 1234
torch.manual_seed(random_seed)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
torch.manual_seed(random_seed)
tensor_5 = torch.rand(2, 3).to(device)
torch.manual_seed(random_seed)
tensor_6 = torch.rand(2, 3).to(device)

tensor_5, tensor_6


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [27]:
# Perform matmul on tensor_A and tensor_B
tensor_5, tensor_5.shape, tensor_6, tensor_6.shape
tensor_7 = tensor_5 @ tensor_6.T
tensor_7, tensor_7.shape

(tensor([[0.2299, 0.2161],
         [0.2161, 0.6287]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
tensor_7.max(), tensor_7.min()
# Find min


(tensor(0.6287, device='cuda:0'), tensor(0.2161, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max
tensor_7.argmax(), tensor_7.argmin()

# Find arg min


(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [34]:
# Set seed
random_seed = 7
torch.manual_seed(random_seed)

# Create random tensor
tensor_8 = torch.rand(1, 1, 1, 10)
tensor_8, tensor_8.shape

# Remove single dimensions
tensor_9 = tensor_8.squeeze()


# Print out tensors and their shapes
tensor_9, tensor_9.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))